AWSTemplateFormatVersion: 2010-09-09
Description: EBS

Parameters:
  ProjectName:
    Type: String
    Default: homework

Resources:
  HomeworkApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: Homework
      Description: AWS ElasticBeanstalk Application Version
      SourceBundle:
        S3Bucket: !Sub '${ProjectName}bucketcodedeploy'
        S3Key: app.zip
  HomeworkConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: Homework
      Description: AWS ElasticBeanstalk Configuration Template
      OptionSettings:
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: '1'
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: '2'
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
      SolutionStackName:  64bit Amazon Linux 2018.03 v2.12.14 running Docker 18.06.1-ce
  HomeworkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: Homework
      Description: AWS ElasticBeanstalk Environment
      TemplateName:
        Ref: HomeworkConfigurationTemplate
      VersionLabel:
        Ref: HomeworkApplicationVersion

Outputs:
  ApplicationURL:
    Description: 'ElasticBeanstalk environment endpoint'
    Value: !Join
      - ''
      - - 'http://'
        - !GetAtt HomeworkEnvironment.EndpointURL
    Export:
      Name: !Sub EnviornmentName